In [1]:
import pandas as pd
import numpy as np

In [2]:
badwords = pd.read_csv('bad-words.csv',names=['words'])

In [3]:
badwords

                           words
jigaboo         English badwords
mound of venus  English badwords
asslover        English badwords
s&m             English badwords
queaf           English badwords
...                          ...
cocky           English badwords
transsexual     English badwords
unfuckable      English badwords
bestiality      English badwords
cocklicker      English badwords

[1617 rows x 1 columns]

In [4]:
badwords['label'] = 'Attack'
bad_tuple =badwords.to_records(index=False)

In [5]:
bad_tuple

rec.array([('English badwords', 'Attack'), ('English badwords', 'Attack'),
           ('English badwords', 'Attack'), ...,
           ('English badwords', 'Attack'), ('English badwords', 'Attack'),
           ('English badwords', 'Attack')],
          dtype=[('words', 'O'), ('label', 'O')])

In [6]:
aggressive_sentences = pd.read_csv('aggression_parsed_dataset.csv')

In [7]:
aggressive_sentences

,index,Text,ed_label_0,ed_label_1,oh_label
0,0,`- This is not ``creative``. Those are the di...,0.900000,0.100000,0
1,1,` :: the term ``standard model`` is itself le...,1.000000,0.000000,0
2,2,"True or false, the situation as of March 200...",1.000000,0.000000,0
3,3,"Next, maybe you could work on being less cond...",0.555556,0.444444,0
4,4,This page will need disambiguation.,1.000000,0.000000,0
...,...,...,...,...,...
115859,115859,` These sources don't exactly exude a sense ...,0.777778,0.222222,0
115860,115860,The Institute for Historical Review is a pee...,1.000000,0.000000,0
115861,115861,:The way you're trying to describe it in this...,1.000000,0.000000,0
115862,115862,== Warning == There is clearly a protection...,0.500000,0.500000,0
115863,115863,Alternate option=== Is there perhaps enough ne...,1.000000,0.000000,0

In [8]:
aggressive_sentences['label'] = np.where(aggressive_sentences['oh_label'] == 1, 'Attack', 'Neutral')
print(aggressive_sentences)

         index                                               Text  ed_label_0  \
0            0  `- This is not ``creative``.  Those are the di...    0.900000
1            1  `  :: the term ``standard model`` is itself le...    1.000000
2            2    True or false, the situation as of March 200...    1.000000
3            3   Next, maybe you could work on being less cond...    0.555556
4            4               This page will need disambiguation.     1.000000
...        ...                                                ...         ...
115859  115859  `   These sources don't exactly exude a sense ...    0.777778
115860  115860    The Institute for Historical Review is a pee...    1.000000
115861  115861   :The way you're trying to describe it in this...    1.000000
115862  115862    == Warning ==  There is clearly a protection...    0.500000
115863  115863  Alternate option=== Is there perhaps enough ne...    1.000000

        ed_label_1  oh_label    label
0         0.100000         0  Neutral
1         0.000000         0  Neutral
2         0.000000         0  Neutral
3         0.444444         0  Neutral
4         0.000000         0  Neutral
...            ...       ...      ...
115859    0.222222         0  Neutral
115860    0.000000         0  Neutral
115861    0.000000         0  Neutral
115862    0.500000         0  Neutral
115863    0.000000         0  Neutral

[115864 rows x 6 columns]

In [9]:
aggressive_sentences=aggressive_sentences.drop(['index','ed_label_0','ed_label_1','oh_label'],axis=1)

In [10]:
attack_sentences = pd.read_csv('attack_parsed_dataset.csv')

In [11]:
attack_sentences.head(100)

,index,Text,ed_label_0,ed_label_1,oh_label
0,0,`- This is not ``creative``. Those are the di...,1.000000,0.000000,0
1,1,` :: the term ``standard model`` is itself le...,1.000000,0.000000,0
2,2,"True or false, the situation as of March 200...",1.000000,0.000000,0
3,3,"Next, maybe you could work on being less cond...",0.555556,0.444444,0
4,4,This page will need disambiguation.,1.000000,0.000000,0
...,...,...,...,...,...
95,95,::Thanks. While I'm attemtping (without any ...,0.950000,0.050000,0
96,96,"Hi Sannse, I answered you question on the ...",1.000000,0.000000,0
97,97,Wikipedia is banned? Why?,1.000000,0.000000,0
98,98,` ::I've been considering the proposed versio...,0.777778,0.222222,0
99,99,Do you think European Union should have th...,1.000000,0.000000,0

In [12]:
attack_sentences['label'] = np.where(attack_sentences['oh_label'] == 1, 'Attack', 'Neutral')
print(attack_sentences)

         index                                               Text  ed_label_0  \
0            0  `- This is not ``creative``.  Those are the di...    1.000000
1            1  `  :: the term ``standard model`` is itself le...    1.000000
2            2    True or false, the situation as of March 200...    1.000000
3            3   Next, maybe you could work on being less cond...    0.555556
4            4               This page will need disambiguation.     1.000000
...        ...                                                ...         ...
115859  115859  `   These sources don't exactly exude a sense ...    0.888889
115860  115860    The Institute for Historical Review is a pee...    0.900000
115861  115861   :The way you're trying to describe it in this...    1.000000
115862  115862    == Warning ==  There is clearly a protection...    0.800000
115863  115863  Alternate option=== Is there perhaps enough ne...    1.000000

        ed_label_1  oh_label    label
0         0.000000         0  Neutral
1         0.000000         0  Neutral
2         0.000000         0  Neutral
3         0.444444         0  Neutral
4         0.000000         0  Neutral
...            ...       ...      ...
115859    0.111111         0  Neutral
115860    0.100000         0  Neutral
115861    0.000000         0  Neutral
115862    0.200000         0  Neutral
115863    0.000000         0  Neutral

[115864 rows x 6 columns]

In [13]:
attack_sentences=attack_sentences.drop(['index','ed_label_0','ed_label_1','oh_label'],axis=1)

In [14]:
kaggle_sentences = pd.read_csv('kaggle_parsed_dataset.csv')

In [15]:
kaggle_sentences.head(100)

,index,oh_label,Date,Text
0,0,1,20120618192155Z,"""You fuck your dad."""
1,1,0,20120528192215Z,"""i really don't understand your point.\xa0 It ..."
2,2,0,NaN,"""A\\xc2\\xa0majority of Canadians can and has ..."
3,3,0,NaN,"""listen if you dont wanna get married to a man..."
4,4,0,20120619094753Z,"""C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd..."
...,...,...,...,...
95,95,1,NaN,"""Correction Bitch! You don't think it's superb..."
96,96,1,20120611215519Z,"""I think the only trickle that effected you wa..."
97,97,1,20120515142854Z,"""And you keep on your knees and keep telling y..."
98,98,0,20120620125953Z,"""What was that, like 2000 words about nothing?..."
99,99,0,20120619032603Z,"""@Rourke needs to give me a fucking like\xa0\x..."

In [16]:
kaggle_sentences['label'] = np.where(kaggle_sentences['oh_label'] == 1, 'Attack', 'Neutral')
print(kaggle_sentences)

      index  oh_label             Date  \
0         0         1  20120618192155Z
1         1         0  20120528192215Z
2         2         0              NaN
3         3         0              NaN
4         4         0  20120619094753Z
...     ...       ...              ...
8794   8794         0  20120612003508Z
8795   8795         0  20120619210456Z
8796   8796         0  20120528234613Z
8797   8797         1  20120619153537Z
8798   8798         0  20120620000237Z

                                                   Text    label
0                                  "You fuck your dad."   Attack
1     "i really don't understand your point.\xa0 It ...  Neutral
2     "A\\xc2\\xa0majority of Canadians can and has ...  Neutral
3     "listen if you dont wanna get married to a man...  Neutral
4     "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...  Neutral
...                                                 ...      ...
8794  "Never really gave it much thought. I just fig...  Neutral
8795                 "Nadie se salva de la regla 34 xd"  Neutral
8796               "Question: Are you a boy or a girl?"  Neutral
8797  "Leave your email or phone number and maybe yo...   Attack
8798  "From the scenarios you present, I see you bel...  Neutral

[8799 rows x 5 columns]

In [17]:
kaggle_sentences=kaggle_sentences.drop(['index','Date','oh_label'],axis=1)

In [18]:
kaggle_sentences

                                                   Text    label
0                                  "You fuck your dad."   Attack
1     "i really don't understand your point.\xa0 It ...  Neutral
2     "A\\xc2\\xa0majority of Canadians can and has ...  Neutral
3     "listen if you dont wanna get married to a man...  Neutral
4     "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...  Neutral
...                                                 ...      ...
8794  "Never really gave it much thought. I just fig...  Neutral
8795                 "Nadie se salva de la regla 34 xd"  Neutral
8796               "Question: Are you a boy or a girl?"  Neutral
8797  "Leave your email or phone number and maybe yo...   Attack
8798  "From the scenarios you present, I see you bel...  Neutral

[8799 rows x 2 columns]

In [19]:
toxicity_sentences = pd.read_csv('toxicity_parsed_dataset.csv')

In [20]:
toxicity_sentences.head(100)

,index,Text,ed_label_0,ed_label_1,oh_label
0,0,This: :One can make an analogy in mathematical...,0.9,0.1,0
1,1,` :Clarification for you (and Zundark's righ...,1.0,0.0,0
2,2,Elected or Electoral? JHK,1.0,0.0,0
3,3,`This is such a fun entry. Devotchka I once...,1.0,0.0,0
4,4,Please relate the ozone hole to increases in c...,0.8,0.2,0
...,...,...,...,...,...
95,95,I wish to apoligize for starting a stressful...,0.9,0.1,0
96,96,"` Um, pardon my ignorance, but what do you ...",1.0,0.0,0
97,97,"Despite Martin's efforts to rescue it, the...",0.8,0.2,0
98,98,MarcusAurelius]] Why exactly was this user b...,0.9,0.1,0
99,99,"` It should be ``bail-out``, with a hyphen. ...",0.9,0.1,0

In [21]:
toxicity_sentences['label'] = np.where(toxicity_sentences['oh_label'] == 1, 'Attack', 'Neutral')
print(toxicity_sentences)

         index                                               Text  ed_label_0  \
0            0  This: :One can make an analogy in mathematical...         0.9
1            1  `  :Clarification for you  (and Zundark's righ...         1.0
2            2                          Elected or Electoral? JHK         1.0
3            3  `This is such a fun entry.   Devotchka  I once...         1.0
4            4  Please relate the ozone hole to increases in c...         0.8
...        ...                                                ...         ...
159681  159681  `   These sources don't exactly exude a sense ...         1.0
159682  159682    The Institute for Historical Review is a pee...         1.0
159683  159683   :The way you're trying to describe it in this...         1.0
159684  159684    == Warning ==  There is clearly a protection...         0.6
159685  159685  Alternate option=== Is there perhaps enough ne...         1.0

        ed_label_1  oh_label    label
0              0.1         0  Neutral
1              0.0         0  Neutral
2              0.0         0  Neutral
3              0.0         0  Neutral
4              0.2         0  Neutral
...            ...       ...      ...
159681         0.0         0  Neutral
159682         0.0         0  Neutral
159683         0.0         0  Neutral
159684         0.4         0  Neutral
159685         0.0         0  Neutral

[159686 rows x 6 columns]

In [22]:
toxicity_sentences=toxicity_sentences.drop(['index','ed_label_0','ed_label_1','oh_label'],axis=1)

In [23]:
toxicity_sentences

                                                     Text    label
0       This: :One can make an analogy in mathematical...  Neutral
1       `  :Clarification for you  (and Zundark's righ...  Neutral
2                               Elected or Electoral? JHK  Neutral
3       `This is such a fun entry.   Devotchka  I once...  Neutral
4       Please relate the ozone hole to increases in c...  Neutral
...                                                   ...      ...
159681  `   These sources don't exactly exude a sense ...  Neutral
159682    The Institute for Historical Review is a pee...  Neutral
159683   :The way you're trying to describe it in this...  Neutral
159684    == Warning ==  There is clearly a protection...  Neutral
159685  Alternate option=== Is there perhaps enough ne...  Neutral

[159686 rows x 2 columns]

In [24]:
twitter_sentences =pd.read_csv('twitter_parsed_dataset.csv')

In [25]:
twitter_sentences.Annotation.unique()

array(['none', 'sexism', 'racism'], dtype=object)

In [26]:
twitter_sentences

,index,id,Text,Annotation,oh_label
0,5.750000e+17,5.750000e+17,@halalflaws @biebervalue @greenlinerzjm I read...,none,0
1,5.720000e+17,5.720000e+17,@ShreyaBafna3 Now you idiots claim that people...,none,0
2,3.900000e+17,3.900000e+17,"RT @Mooseoftorment Call me sexist, but when I ...",sexism,1
3,5.680000e+17,5.680000e+17,"@g0ssipsquirrelx Wrong, ISIS follows the examp...",racism,1
4,5.760000e+17,5.760000e+17,#mkr No No No No No No,none,0
...,...,...,...,...,...
16844,5.760000e+17,5.760000e+17,"Feeling so sorry for the girls, they should be...",none,0
16845,5.720000e+17,5.720000e+17,#MKR 'pretty good dishes we're happy with' - O...,none,0
16846,5.720000e+17,5.720000e+17,RT @colonelkickhead: Deconstructed lemon tart!...,none,0
16847,5.750000e+17,5.750000e+17,@versacezaynx @nyazpolitics @greenlinerzjm You...,none,0
16848,5.690000e+17,5.690000e+17,"And before you protest that you're *not* mad, ...",none,0

In [27]:
conds = [twitter_sentences['Annotation'].isin(['sexism']),
         twitter_sentences['Annotation'].isin(['racism']),
        twitter_sentences['Annotation'].isin(['Nuetral'])]
values = ['Attack', 'Attack','Nuetral']
twitter_sentences['label'] = np.select(conds, values, default='Nuetral')


print(twitter_sentences)

              index            id  \
0      5.750000e+17  5.750000e+17
1      5.720000e+17  5.720000e+17
2      3.900000e+17  3.900000e+17
3      5.680000e+17  5.680000e+17
4      5.760000e+17  5.760000e+17
...             ...           ...
16844  5.760000e+17  5.760000e+17
16845  5.720000e+17  5.720000e+17
16846  5.720000e+17  5.720000e+17
16847  5.750000e+17  5.750000e+17
16848  5.690000e+17  5.690000e+17

                                                    Text Annotation  oh_label  \
0      @halalflaws @biebervalue @greenlinerzjm I read...       none         0
1      @ShreyaBafna3 Now you idiots claim that people...       none         0
2      RT @Mooseoftorment Call me sexist, but when I ...     sexism         1
3      @g0ssipsquirrelx Wrong, ISIS follows the examp...     racism         1
4                                 #mkr No No No No No No       none         0
...                                                  ...        ...       ...
16844  Feeling so sorry for the girls, they should be...       none         0
16845  #MKR 'pretty good dishes we're happy with' - O...       none         0
16846  RT @colonelkickhead: Deconstructed lemon tart!...       none         0
16847  @versacezaynx @nyazpolitics @greenlinerzjm You...       none         0
16848  And before you protest that you're *not* mad, ...       none         0

         label
0      Nuetral
1      Nuetral
2       Attack
3       Attack
4      Nuetral
...        ...
16844  Nuetral
16845  Nuetral
16846  Nuetral
16847  Nuetral
16848  Nuetral

[16849 rows x 6 columns]

In [28]:
twitter_sentences=twitter_sentences.drop(['index','id','Annotation','oh_label'],axis=1)

In [29]:
twitter_sentences

                                                    Text    label
0      @halalflaws @biebervalue @greenlinerzjm I read...  Nuetral
1      @ShreyaBafna3 Now you idiots claim that people...  Nuetral
2      RT @Mooseoftorment Call me sexist, but when I ...   Attack
3      @g0ssipsquirrelx Wrong, ISIS follows the examp...   Attack
4                                 #mkr No No No No No No  Nuetral
...                                                  ...      ...
16844  Feeling so sorry for the girls, they should be...  Nuetral
16845  #MKR 'pretty good dishes we're happy with' - O...  Nuetral
16846  RT @colonelkickhead: Deconstructed lemon tart!...  Nuetral
16847  @versacezaynx @nyazpolitics @greenlinerzjm You...  Nuetral
16848  And before you protest that you're *not* mad, ...  Nuetral

[16849 rows x 2 columns]

In [30]:
twitter_racism_sentences= pd.read_csv('twitter_racism_parsed_dataset.csv')

In [31]:
twitter_racism_sentences.Annotation.unique()

array(['racism', 'none'], dtype=object)

In [32]:
twitter_racism_sentences.head()

,index,id,Text,Annotation,oh_label
0,5.767493e+17,5.767493e+17,@AAlwuhaib1977 Muslim mob violence against Hin...,racism,1
1,5.408905e+17,5.408905e+17,@Te4m_NiGhtM4Re http://t.co/5Ih7MkDbQG,none,0
2,5.678433e+17,5.678433e+17,@jncatron @isra_jourisra @AMPalestine Islamoph...,racism,1
3,5.766462e+17,5.766462e+17,"Finally I'm all caught up, and that sudden dea...",none,0
4,5.713492e+17,5.713492e+17,@carolinesinders @herecomesfran *hugs*,none,0

In [33]:
twitter_racism_sentences['label'] = np.where(twitter_racism_sentences['Annotation'] == 'racism', 'Attack', 'Neutral')
print(twitter_racism_sentences)

              index            id  \
0      5.767493e+17  5.767493e+17
1      5.408905e+17  5.408905e+17
2      5.678433e+17  5.678433e+17
3      5.766462e+17  5.766462e+17
4      5.713492e+17  5.713492e+17
...             ...           ...
13466  5.755964e+17  5.755964e+17
13467  5.580631e+17  5.580631e+17
13468  5.755969e+17  5.755969e+17
13469  5.755990e+17  5.755990e+17
13470  5.755977e+17  5.755977e+17

                                                    Text Annotation  oh_label  \
0      @AAlwuhaib1977 Muslim mob violence against Hin...     racism         1
1                 @Te4m_NiGhtM4Re http://t.co/5Ih7MkDbQG       none         0
2      @jncatron @isra_jourisra @AMPalestine Islamoph...     racism         1
3      Finally I'm all caught up, and that sudden dea...       none         0
4                 @carolinesinders @herecomesfran *hugs*       none         0
...                                                  ...        ...       ...
13466   #mkr NOOOOO!!! I wanted Kat and Andre to lose!!!       none         0
13467  RT @MumtazCeltik: @WhiteHouse @VP \n\n#Kobane ...       none         0
13468  Glad the proper competition is starting and ev...       none         0
13469  No worries Pete and Manu, take all the time of...       none         0
13470  @mykitchenrules #mkr please kick off that lady...       none         0

         label
0       Attack
1      Neutral
2       Attack
3      Neutral
4      Neutral
...        ...
13466  Neutral
13467  Neutral
13468  Neutral
13469  Neutral
13470  Neutral

[13471 rows x 6 columns]

In [34]:
twitter_racism_sentences=twitter_racism_sentences.drop(['index','id','Annotation','oh_label'],axis=1)

In [35]:
twitter_racism_sentences

                                                    Text    label
0      @AAlwuhaib1977 Muslim mob violence against Hin...   Attack
1                 @Te4m_NiGhtM4Re http://t.co/5Ih7MkDbQG  Neutral
2      @jncatron @isra_jourisra @AMPalestine Islamoph...   Attack
3      Finally I'm all caught up, and that sudden dea...  Neutral
4                 @carolinesinders @herecomesfran *hugs*  Neutral
...                                                  ...      ...
13466   #mkr NOOOOO!!! I wanted Kat and Andre to lose!!!  Neutral
13467  RT @MumtazCeltik: @WhiteHouse @VP \n\n#Kobane ...  Neutral
13468  Glad the proper competition is starting and ev...  Neutral
13469  No worries Pete and Manu, take all the time of...  Neutral
13470  @mykitchenrules #mkr please kick off that lady...  Neutral

[13471 rows x 2 columns]

In [36]:
twitter_sexism_sentences = pd.read_csv('twitter_sexism_parsed_dataset.csv')

In [37]:
twitter_sexism_sentences.head()

,index,id,Text,Annotation,oh_label
0,5.35198627292254E+017,5.35198627292254E+017,RT @BeepsS: @senna1 @BeepsS: I'm not sexist bu...,sexism,1.0
1,5.75984924030714E+017,5.75984924030714E+017,There's some very hate able teams this year #MKR,none,0.0
2,5.7233536016588E+017,5.7233536016588E+017,"RT @The_Eccles: ""Everyone underestimated us"" \...",none,0.0
3,5.72337925708374E+017,5.72337925708374E+017,RT @NOTLukeDarcy: did @Channel7 or #MKR actual...,none,0.0
4,4.43033024528011E+017,4.43033024528011E+017,"No, you don't. @Shut_Up_Jeff: I thought of a r...",sexism,1.0

In [38]:
twitter_sexism_sentences.Annotation.unique()

array(['sexism', 'none', nan], dtype=object)

In [39]:
twitter_sexism_sentences = twitter_sexism_sentences[twitter_sexism_sentences['Annotation'].notna()]

In [40]:
twitter_sexism_sentences['label'] = np.where(twitter_sexism_sentences['Annotation'] == 'sexism', 'Attack', 'Neutral')
print(twitter_sexism_sentences)

                       index                     id  \
0      5.35198627292254E+017  5.35198627292254E+017
1      5.75984924030714E+017  5.75984924030714E+017
2       5.7233536016588E+017   5.7233536016588E+017
3      5.72337925708374E+017  5.72337925708374E+017
4      4.43033024528011E+017  4.43033024528011E+017
...                      ...                    ...
14876  5.76422824501379E+017  5.76422824501379E+017
14877  4.64045547473498E+017  4.64045547473498E+017
14878  5.54705698508919E+017  5.54705698508919E+017
14879   5.7560079584598E+017   5.7560079584598E+017
14880  5.67826532711862E+017  5.67826532711862E+017

                                                    Text Annotation  oh_label  \
0      RT @BeepsS: @senna1 @BeepsS: I'm not sexist bu...     sexism       1.0
1       There's some very hate able teams this year #MKR       none       0.0
2      RT @The_Eccles: "Everyone underestimated us" \...       none       0.0
3      RT @NOTLukeDarcy: did @Channel7 or #MKR actual...       none       0.0
4      No, you don't. @Shut_Up_Jeff: I thought of a r...     sexism       1.0
...                                                  ...        ...       ...
14876  @RaikonL @finaleve @mja333 WHY DO YOU HATE FRE...       none       0.0
14877  It is unconscionable that our regulatory bodie...       none       0.0
14878  @Dartanveerahmad @Janx53 @geehall1 We want ISI...       none       0.0
14879  #mkr  Unbelievable how low Kat &amp; Andre wil...       none       0.0
14880  RT @JamesMakienko: @omeisy @yemenrightsmon Peo...       none       0.0

         label
0       Attack
1      Neutral
2      Neutral
3      Neutral
4       Attack
...        ...
14876  Neutral
14877  Neutral
14878  Neutral
14879  Neutral
14880  Neutral

[14878 rows x 6 columns]

In [41]:
twitter_sexism_sentences=twitter_sexism_sentences.drop(['index','id','Annotation','oh_label'],axis=1)

In [42]:
twitter_sexism_sentences

                                                    Text    label
0      RT @BeepsS: @senna1 @BeepsS: I'm not sexist bu...   Attack
1       There's some very hate able teams this year #MKR  Neutral
2      RT @The_Eccles: "Everyone underestimated us" \...  Neutral
3      RT @NOTLukeDarcy: did @Channel7 or #MKR actual...  Neutral
4      No, you don't. @Shut_Up_Jeff: I thought of a r...   Attack
...                                                  ...      ...
14876  @RaikonL @finaleve @mja333 WHY DO YOU HATE FRE...  Neutral
14877  It is unconscionable that our regulatory bodie...  Neutral
14878  @Dartanveerahmad @Janx53 @geehall1 We want ISI...  Neutral
14879  #mkr  Unbelievable how low Kat &amp; Andre wil...  Neutral
14880  RT @JamesMakienko: @omeisy @yemenrightsmon Peo...  Neutral

[14878 rows x 2 columns]

In [43]:
youtube_sentences =pd.read_csv('youtube_parsed_dataset.csv')

In [44]:
youtube_sentences.head

<bound method NDFrame.head of       index UserIndex                                               Text  \
0         0        X1  Does N.e.bodyelse Hear her Crazy ass Screamin ...
1         1        X2  There are so many things that are incorrect wi...
2         2        X3  3:26 hahah my boyfriend showed this song to me...
3         3     X2218  dick beyonce fuck y a ass hole you are truely ...
4         4        X5  DongHaeTaemin and Kai ;A; luhansehun and bacon...
...     ...       ...                                                ...
3459   3464     X3465  She pretty I love this song I miss the old kel...
3460   3465     X3466  Status-Online Im ZxkillergirlzX! I'm Zxkillerg...
3461   3466     X3467  JR so cute EXO M Better I agree like yeah yeah...
3462   3467     X3468                                                ! !
3463   3468     X3469  great video and MERRY CHRISTMAS from greece :*...

      Number of Comments  Number of Subscribers  Membership Duration  \
0                     10                      1                    3
1                      3                      0                    6
2                      7                      0                    3
3                     34                      0                    3
4                     11                    173                    5
...                  ...                    ...                  ...
3459                  15                      2                    4
3460                   4                     28                    4
3461                  23                      0                    5
3462                   5                      0                    6
3463                  27                    220                    4

      Number of Uploads  Profanity in UserID  Age  oh_label
0                     3                    0   15         0
1                     5                    0   31         0
2                     5                    0   43         1
3                     5                    0   44         1
4                     5                    0   21         0
...                 ...                  ...  ...       ...
3459                  7                    0   23         1
3460                 23                    1   15         0
3461                  3                    0   33         0
3462                  5                    0   38         0
3463                 30                    0   18         0

[3464 rows x 10 columns]>

In [45]:
youtube_sentences['label'] = np.where(youtube_sentences['oh_label'] == 1, 'Attack', 'Neutral')
print(youtube_sentences)

      index UserIndex                                               Text  \
0         0        X1  Does N.e.bodyelse Hear her Crazy ass Screamin ...
1         1        X2  There are so many things that are incorrect wi...
2         2        X3  3:26 hahah my boyfriend showed this song to me...
3         3     X2218  dick beyonce fuck y a ass hole you are truely ...
4         4        X5  DongHaeTaemin and Kai ;A; luhansehun and bacon...
...     ...       ...                                                ...
3459   3464     X3465  She pretty I love this song I miss the old kel...
3460   3465     X3466  Status-Online Im ZxkillergirlzX! I'm Zxkillerg...
3461   3466     X3467  JR so cute EXO M Better I agree like yeah yeah...
3462   3467     X3468                                                ! !
3463   3468     X3469  great video and MERRY CHRISTMAS from greece :*...

      Number of Comments  Number of Subscribers  Membership Duration  \
0                     10                      1                    3
1                      3                      0                    6
2                      7                      0                    3
3                     34                      0                    3
4                     11                    173                    5
...                  ...                    ...                  ...
3459                  15                      2                    4
3460                   4                     28                    4
3461                  23                      0                    5
3462                   5                      0                    6
3463                  27                    220                    4

      Number of Uploads  Profanity in UserID  Age  oh_label    label
0                     3                    0   15         0  Neutral
1                     5                    0   31         0  Neutral
2                     5                    0   43         1   Attack
3                     5                    0   44         1   Attack
4                     5                    0   21         0  Neutral
...                 ...                  ...  ...       ...      ...
3459                  7                    0   23         1   Attack
3460                 23                    1   15         0  Neutral
3461                  3                    0   33         0  Neutral
3462                  5                    0   38         0  Neutral
3463                 30                    0   18         0  Neutral

[3464 rows x 11 columns]

In [46]:
youtube_sentences=youtube_sentences.drop(['index','UserIndex','Number of Comments','Number of Subscribers','Membership Duration','Number of Uploads','Profanity in UserID','Age','oh_label'],axis=1)

In [47]:
youtube_sentences

                                                   Text    label
0     Does N.e.bodyelse Hear her Crazy ass Screamin ...  Neutral
1     There are so many things that are incorrect wi...  Neutral
2     3:26 hahah my boyfriend showed this song to me...   Attack
3     dick beyonce fuck y a ass hole you are truely ...   Attack
4     DongHaeTaemin and Kai ;A; luhansehun and bacon...  Neutral
...                                                 ...      ...
3459  She pretty I love this song I miss the old kel...   Attack
3460  Status-Online Im ZxkillergirlzX! I'm Zxkillerg...  Neutral
3461  JR so cute EXO M Better I agree like yeah yeah...  Neutral
3462                                                ! !  Neutral
3463  great video and MERRY CHRISTMAS from greece :*...  Neutral

[3464 rows x 2 columns]

In [48]:
badwords.rename(columns = {'words':'Text'}, inplace = True)

In [49]:
train_sentences =pd.read_csv('train.csv')

In [50]:
conds = [train_sentences['toxic']== 1,
         train_sentences['severe_toxic']==1,
        train_sentences['obscene']==1,
        train_sentences['threat']==1,
        train_sentences['insult']==1,
        train_sentences['identity_hate']==1]
values = ['Attack', 'Attack','Attack', 'Attack','Attack','Attack']
train_sentences['label'] = np.select(conds, values, default='Nuetral')


print(train_sentences)

                      id                                       comment_text  \
0       0000997932d777bf  Explanation\nWhy the edits made under my usern...
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...
3       0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...
...                  ...                                                ...
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...

        toxic  severe_toxic  obscene  threat  insult  identity_hate    label
0           0             0        0       0       0              0  Nuetral
1           0             0        0       0       0              0  Nuetral
2           0             0        0       0       0              0  Nuetral
3           0             0        0       0       0              0  Nuetral
4           0             0        0       0       0              0  Nuetral
...       ...           ...      ...     ...     ...            ...      ...
159566      0             0        0       0       0              0  Nuetral
159567      0             0        0       0       0              0  Nuetral
159568      0             0        0       0       0              0  Nuetral
159569      0             0        0       0       0              0  Nuetral
159570      0             0        0       0       0              0  Nuetral

[159571 rows x 9 columns]

In [51]:
train_sentences=train_sentences.drop(['id','toxic','severe_toxic','obscene','threat','insult','identity_hate'],axis=1)

In [52]:
train_sentences.rename(columns = {'comment_text':'Text'}, inplace = True)

In [53]:
train_sentences

                                                     Text    label
0       Explanation\nWhy the edits made under my usern...  Nuetral
1       D'aww! He matches this background colour I'm s...  Nuetral
2       Hey man, I'm really not trying to edit war. It...  Nuetral
3       "\nMore\nI can't make any real suggestions on ...  Nuetral
4       You, sir, are my hero. Any chance you remember...  Nuetral
...                                                   ...      ...
159566  ":::::And for the second time of asking, when ...  Nuetral
159567  You should be ashamed of yourself \n\nThat is ...  Nuetral
159568  Spitzer \n\nUmm, theres no actual article for ...  Nuetral
159569  And it looks like it was actually you who put ...  Nuetral
159570  "\nAnd ... I really don't think you understand...  Nuetral

[159571 rows x 2 columns]

In [54]:
print (pd.concat([youtube_sentences, twitter_sexism_sentences, twitter_racism_sentences, twitter_sentences, toxicity_sentences,kaggle_sentences,attack_sentences,aggressive_sentences,badwords,train_sentences], ignore_index=True))

                                                     Text    label
0       Does N.e.bodyelse Hear her Crazy ass Screamin ...  Neutral
1       There are so many things that are incorrect wi...  Neutral
2       3:26 hahah my boyfriend showed this song to me...   Attack
3       dick beyonce fuck y a ass hole you are truely ...   Attack
4       DongHaeTaemin and Kai ;A; luhansehun and bacon...  Neutral
...                                                   ...      ...
610058  ":::::And for the second time of asking, when ...  Nuetral
610059  You should be ashamed of yourself \n\nThat is ...  Nuetral
610060  Spitzer \n\nUmm, theres no actual article for ...  Nuetral
610061  And it looks like it was actually you who put ...  Nuetral
610062  "\nAnd ... I really don't think you understand...  Nuetral

[610063 rows x 2 columns]

In [55]:
df= pd.concat([youtube_sentences, twitter_sexism_sentences, twitter_racism_sentences, twitter_sentences, toxicity_sentences,kaggle_sentences,attack_sentences,aggressive_sentences,badwords,train_sentences], ignore_index=True)

In [56]:
df

                                                     Text    label
0       Does N.e.bodyelse Hear her Crazy ass Screamin ...  Neutral
1       There are so many things that are incorrect wi...  Neutral
2       3:26 hahah my boyfriend showed this song to me...   Attack
3       dick beyonce fuck y a ass hole you are truely ...   Attack
4       DongHaeTaemin and Kai ;A; luhansehun and bacon...  Neutral
...                                                   ...      ...
610058  ":::::And for the second time of asking, when ...  Nuetral
610059  You should be ashamed of yourself \n\nThat is ...  Nuetral
610060  Spitzer \n\nUmm, theres no actual article for ...  Nuetral
610061  And it looks like it was actually you who put ...  Nuetral
610062  "\nAnd ... I really don't think you understand...  Nuetral

[610063 rows x 2 columns]

In [57]:
df.to_csv('finaldf.csv')

In [58]:

df_tuple =df.to_records(index=False)

In [59]:
df_tuple

rec.array([("Does N.e.bodyelse Hear her Crazy ass Screamin ,HOE, everytime she say's Stupid Hoe .. Lol. did n.e.body see Chris Browns face at 2:04 wen Nicki was touchin him If you worked out we wouldn't be lookin at that Body D: She looks so tired :/ She has ah Tatto on her ass Wtf is this o.O Instagram Deze Nutt's In Yo Mouth Lmao This Video/Song made me ah Lil. Umm . . . .In the mood .___. We're all in this together motherfucka Wow you have an amazing voice. And I've never said that about anyone.", 'Neutral'),
           ("There are so many things that are incorrect with your comment it's unbelievable. Guns don't kill people. A gun doesn't get up off a table and then shoot someone. He's not the reason soldiers are at war he's merely showing us weapons and explaining how they work and whether he likes them or not. You blame him for violent video games...Why would this guy mess around with video games when he has real weapons he can use and practice with. I can't say much more coz I don't have more space. Retard. This is all we need an Australian version of 1 Direction.... my dick was bleeding from how hard I was masturbating to this", 'Neutral'),
           ('3:26 hahah my boyfriend showed this song to me I love it Me tooo Is she having a seizure. Omg u have a corgi I am training for the Olympics and I am Russian You want some rapes... LOL', 'Attack'),
           ...,
           ('Spitzer \n\nUmm, theres no actual article for prostitution ring.  - Crunch Captain.', 'Nuetral'),
           ('And it looks like it was actually you who put on the speedy to have the first version deleted now that I look at it.', 'Nuetral'),
           ('"\nAnd ... I really don\'t think you understand.  I came here and my idea was bad right away.  What kind of community goes ""you have bad ideas"" go away, instead of helping rewrite them.   "', 'Nuetral')],
          dtype=[('Text', 'O'), ('label', 'O')])

In [60]:
import math
from creme import compose
from creme import feature_extraction
from creme import naive_bayes
import creme
model = compose.Pipeline(
    ('tokenize', feature_extraction.TFIDF(lowercase=False)),
    ('nb', naive_bayes.MultinomialNB(alpha=1))
)

In [61]:
from creme import metrics
metric=metrics.Accuracy()
# Training the model row by row
for Text,label in df_tuple:
    model = model.fit_one(Text, label)
    y_pred = model.predict_one(Text)
    metric = metric.update(label, y_pred)

In [62]:
metric

Accuracy: 65.92%

In [68]:
model.predict_one("stupidly good")

'Neutral'

In [64]:
text ="Sure, heres an example of a YouTube script for the PowerPoint presentation on time management:Title: Mastering Time Management: Tips and StrategiesIntroduction:Hey everyone, welcome back to my channel! In this video, were going to be talking about time management and how to make the most of your day. Time management is an essential skill that can help you be more productive and achieve your goals. So if you're ready to take control of your time, then keep watching!Definition of Time Management:Let"

In [65]:
text.split(':')

['Sure, heres an example of a YouTube script for the PowerPoint presentation on time management',
 'Title',
 ' Mastering Time Management',
 ' Tips and StrategiesIntroduction',
 "Hey everyone, welcome back to my channel! In this video, were going to be talking about time management and how to make the most of your day. Time management is an essential skill that can help you be more productive and achieve your goals. So if you're ready to take control of your time, then keep watching!Definition of Time Management",
 'Let']

In [66]:
model.save()

AttributeError: 'Pipeline' object has no attribute 'save'